name: "Bump `docker-registry` helm chart version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: docker-registry

targets:
  updateChartVersion:
    name: "Update the chart version for docker-registry"
    kind: yaml
    spec:
      files:
        - clusters/cijioagents2.yaml
      engine: yamlpath
      key: $.releases[?(@.chart == 'jenkins-infra/docker-registry')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `docker-registry` helm chart version to {{ source `lastChartVersion` }}
    spec:
      labels:
        - dependencies
        - docker-registry
