providers:
  aks:
    enabled: true
datadog:
  clusterName: 'infracijioagents2'
  env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
clusterAgent:
  nodeSelector:
    kubernetes.io/arch: arm64
    kubernetes.azure.com/mode: system
  # allow to start on system nodepool
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
agents:
  tolerations:
    # These tolerations are needed to run the agents on all the pools
    - key: "infra.ci.jenkins.io/agents"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
